package com.example.kjumpble.ble.cmd;

public enum BLE_CMD {
    READ_SETTING_STEP_1,
    READ_SETTING_STEP_2,
    CONFIRM_USER_AND_MEMORY,
    CONFIRM_NUMBER_OF_DATA,
    READ_DATA,
    CLEAR_DATA,
    READ_TEMPERATURE_UNIT_AND_HAND,
    WRITE_PRE_CLOCK,
    WRITE_POST_CLOCK,
    WRITE_CLOCK_FLAG,
    WRITE_REMINDER_CLOCK,
    WRITE_SET,
    WRITE_AMBIENT,
    WRITE_OFFSET,
    WRITE_BEEP,
    WRITE_UNIT,
    WRITE_HAND,
    WRITE_TEMPERATURE_UNIT_AND_HAND,
    NUMBER_OF_DATA_ZERO,
}
