package com.example.kjumpble.ble.cmd;

public enum BLE_CMD {
    CONFIRM_USER_AND_MEMORY,
    CONFIRM_NUMBER_OF_DATA,
    READ_DATA,
    CLEAR_DATA,
    WRITE_PRE_CLOCK,
    WRITE_POST_CLOCK,
    WRITE_REMINDER_CLOCK,
    WRITE_REFRESH,
    WRITE_UNIT,
    NUMBER_OF_DATA_ZERO,
}
