package com.example.kjumpble.ble.cmd;

public enum BLE_CMD {
    CONFIRM_USER_AND_MEMORY,
    CONFIRM_NUMBER_OF_DATA,
    READ_DATA,
    CLEAR_DATA,
    READ_TEMPERATURE_UNIT_AND_HAND,
    WRITE_PRE_CLOCK,
    WRITE_POST_CLOCK,
    WRITE_REMINDER_CLOCK,
    WRITE_SET,
    WRITE_UNIT,
    WRITE_HAND,
    WRITE_TEMPERATURE_UNIT_AND_HAND,
    NUMBER_OF_DATA_ZERO,
}
